import Head from 'next/head';
import './global.scss';

export const metadata = {
  title: 'Nx Next App',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Head>
        <title>Welcome to budget-ui!</title>
      </Head>
      <body>{children}</body>
    </html>
  );
}
